######################################################################
# Automatically generated by qmake (3.0) ?? ?? 15 17:37:40 2017
######################################################################
TEMPLATE = subdirs
TARGET = souieditor
CONFIG(x64){
TARGET = $$TARGET"64"
}
DEPENDPATH += .
INCLUDEPATH += .

SUBDIRS += ExtendCtrls
SUBDIRS += uieditor
SUBDIRS += uiviewer

uieditor.depends += ExtendCtrls
uiviewer.depends += ExtendCtrls